### ISSUE TITLE
les docs joints au script n'apparaissent pas en vue publique.

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_air_laclasse#10]
![bug fichier joint script air](https://user-images.githubusercontent.com/7963908/65029560-462c0300-d93e-11e9-954c-885a7e1146b8.png)

**Comment by heleroy** [comment]
En fait,  quand on ajoute un doc joint au script de l'hist 1 chapitre 1, il s'affiche sur le chapitre 1 de l'histoire 3. Indice provenance : duplication ?

**Comment by racine-p-a** [comment]
Ils apparaissent bien -> mauvais affichage des colonnes.
