### ISSUE TITLE
afficher les mêmes nombres de caractères pour les fins de chapitre selon les différents endroits

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_air_laclasse#2]
En effet, si on va sur la page d'accueil, en passant la souris sur le chapitre 1 on voit moins de texte que si on ouvre un histoire sur laquelle on n'a pas les droits (sur la colonne droite - cf capture
![capture du 2017-09-29 11-12-11](https://user-images.githubusercontent.com/7963908/31009284-36138776-a507-11e7-9f25-1d868b47da69.png)
![capture du 2017-09-29 11-08-31](https://user-images.githubusercontent.com/7963908/31009283-360fded2-a507-11e7-8ddf-9ed3fdeff807.png)

)

**Comment by heleroy** [comment]
Question : d'ailleurs je ne sais pas si c'est normal d'avoir la vue avec le cadena (capture de l'histoire sur laquelle on n'a pas de droits). On ne devrait pas pouvoir visualiser quand même les scripts et forums des autres histoires  que celle sur laquelle on doit travailler ?

**Comment by racine-p-a** [comment]
Vérifier que la troncature du texte est identique aux deux endroits.

**Comment by racine-p-a** [comment]
Troncature corrigée.
