### ISSUE TITLE
ouverture de fichiers joints aux articles du site qui mouline (en front seulement)

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_air_laclasse#3]
exemple sur les documents joints au script du chapitre 1 de n'importe quelle histoire de l'année 2017-2018. Sur l'arrière cuisine du site, les pièces jointes s'ouvrent bien et aussi ceux du forum.
![capture](https://user-images.githubusercontent.com/7963908/32228024-4d7255e6-be4d-11e7-9cf1-c5c463e14d1c.PNG)

**Comment by racine-p-a** [comment]
fait par yassine
