### ISSUE TITLE
Notifications sur le forum général qui doivent être envoyées à tous 

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_air_laclasse#5]
créer une règle de redirection pour la notification par mail pour ne pas que le lien de l'article soit affiché dans le mail de notif mais plutôt le lien vers l'agora.
![capture air issue github ccnum air](https://user-images.githubusercontent.com/7963908/36673250-7652a49a-1b02-11e8-9739-8f2c80e5fd4c.PNG)

**Comment by heleroy** [comment]
en attendant que le bug soit corrigé on active l'envoi des notifications à la liste de diffusion.

**Comment by racine-p-a** [comment]
À fermer en attente de retour du besoin.
