### ISSUE TITLE
Réactiver les droits d'admin restreint

### ISSUE THREAD

**Issue by celiacbo** [ccnum/plugin_air_laclasse#6]
Impossible de donner des droits d'admin restreint aux nouveaux utilisateurs que je crée pour les projets de petit fablab d'écriture (basé sur la rubrique "jeu") ; je vois bien qu'une option devrait apparaître en BO pour choisir une rubrique précise et limiter leurs droits d'administration mais ça apparaît avec la barre de défilement tronquée.

**Comment by racine-p-a** [comment]
résolu par petitfablab.com
