### ISSUE TITLE
PETIT FABLAB - Erreurs dans le squelette

### ISSUE THREAD

**Issue by cbo04** [ccnum/plugin_air_laclasse#74]
<img width="1347" alt="Capture d’écran 2022-11-30 à 10 59 42" src="https://user-images.githubusercontent.com/77880887/204770269-3fcf2857-0619-401e-8aa8-f54a32041bf3.png">

**Comment by racine-p-a** [comment]
2af5b1fa439251e21286c81b52b3ea7a15a76bc2
