### ISSUE TITLE
PETIT FABLAB - overlap screen size 13"

### ISSUE THREAD

**Issue by cbo04** [ccnum/plugin_air_laclasse#75]
<img width="1353" alt="Capture d’écran 2022-11-30 à 10 51 43" src="https://user-images.githubusercontent.com/77880887/204770469-b9131048-672b-4c83-9b0f-dae9bd3b6fb4.png">
<img width="1356" alt="Capture d’écran 2022-11-30 à 10 59 30" src="https://user-images.githubusercontent.com/77880887/204770479-edb6caaf-eef6-43a0-97ad-5fd8b4555e2e.png">

**Comment by racine-p-a** [comment]
Corrigé en même temps qu'issue précédente. Le débordement est causé par les erreurs SPIP qui cassaient le CSS.
2af5b1fa439251e21286c81b52b3ea7a15a76bc2
