### ISSUE TITLE
Affichage du lien vers l'espace doc / ciblé sur le groupe libre "AIR 2019"

### ISSUE THREAD

**Issue by heleroy** [ccnum/plugin_air_laclasse#9]
à afficher en bas du site
Le lien se renseigne dans le plug-in thématique (cf rubrique "configuration de l'espace docs" sur la "Documentation back").

**Comment by racine-p-a** [comment]
Hélène me donne une url et je l'ajoute dans le footer, cette url sera à modifier chaque année. Mettre dans la documentation que cela doit être modifié chaque année.
